"""Learning Agent — the self-improvement loop.

Analyzes published videos + their analytics to learn what works: best hook types,
best categories, best durations. Writes durable findings to `ai_memory` and emits
a machine-readable `config/learned_rules.yaml` that other agents/prompts can read
to bias future decisions — closing the create → measure → improve loop.
"""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path

import yaml

from core.agents.base import BaseAgent
from core.config import ROOT_DIR
from core.database.models import AIMemory, Analytics, Content, ContentMemory
from core.database.session import session_scope
from core.registry import register_agent


@register_agent
class LearningAgent(BaseAgent):
    name = "learning"
    folder = "learning_agent"

    def run(self, payload: dict | None = None) -> dict:
        min_samples = self.config.get("min_samples", 3)
        with session_scope() as s:
            rows = (
                s.query(ContentMemory, Content)
                .join(Content, Content.id == ContentMemory.video_id)
                .filter(Content.status == "published")
                .all()
            )
            retention = self._avg_retention(s)

        by_hook: dict[str, list[float]] = defaultdict(list)
        by_category: dict[str, list[float]] = defaultdict(list)
        by_duration: dict[str, list[float]] = defaultdict(list)

        for mem, content in rows:
            score = mem.performance_score or 0.0
            if mem.hook_type:
                by_hook[mem.hook_type].append(score)
            by_category[content.category].append(score)
            bucket = self._duration_bucket(mem.duration or 0)
            by_duration[bucket].append(score)

        insights = {
            "samples": len(rows),
            "best_hook_type": self._best(by_hook, min_samples),
            "best_category": self._best(by_category, min_samples),
            "best_duration_bucket": self._best(by_duration, min_samples),
            "avg_retention": retention,
        }
        self._persist_memory(insights, by_hook, by_category)
        rules = self._write_rules(insights)
        self.log.info("Learning: %s", {k: v for k, v in insights.items() if k != "samples"})
        return {"insights": insights, "rules_written_to": rules}

    # ── helpers ────────────────────────────────────────────────────────────
    def _best(self, groups: dict[str, list[float]], min_samples: int) -> dict | None:
        eligible = {k: sum(v) / len(v) for k, v in groups.items() if len(v) >= min_samples}
        if not eligible:
            return None
        key = max(eligible, key=eligible.get)
        return {"value": key, "avg_score": round(eligible[key], 1),
                "samples": len(groups[key])}

    def _duration_bucket(self, seconds: float) -> str:
        if seconds <= 30:
            return "0-30s"
        if seconds <= 60:
            return "30-60s"
        if seconds <= 90:
            return "60-90s"
        return "90s+"

    def _avg_retention(self, session) -> float:
        vals = [a.retention for a in session.query(Analytics).all() if a.retention]
        return round(sum(vals) / len(vals), 1) if vals else 0.0

    def _persist_memory(self, insights: dict, by_hook, by_category) -> None:
        with session_scope() as s:
            for kind, groups in (("hook", by_hook), ("category", by_category)):
                for key, scores in groups.items():
                    if not scores:
                        continue
                    avg = sum(scores) / len(scores)
                    s.add(AIMemory(
                        kind=kind, key=key,
                        outcome="worked" if avg >= 60 else "failed",
                        score=round(avg, 1), samples=len(scores),
                        detail={"insight_snapshot": insights.get(f"best_{kind}")},
                    ))

    def _write_rules(self, insights: dict) -> str:
        path = ROOT_DIR / self.config.get("learned_rules_path", "config/learned_rules.yaml")
        path.parent.mkdir(parents=True, exist_ok=True)
        rules = {
            "updated_from_samples": insights["samples"],
            "prefer_hook_type": (insights["best_hook_type"] or {}).get("value"),
            "prefer_category_bias": (insights["best_category"] or {}).get("value"),
            "prefer_duration_bucket": (insights["best_duration_bucket"] or {}).get("value"),
            "note": "Auto-generated by the Learning Agent. Consumed by topic/hook/script prompts.",
        }
        path.write_text(yaml.safe_dump(rules, sort_keys=False), encoding="utf-8")
        return str(path)
